name: Build Android APK

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to your project's Expo account."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: pnpm install

      - name: Build APK
        run: eas build --platform android --profile preview --local --non-interactive --output=./app-release.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app-release.apk
